apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-pod
  template:
    metadata:
      labels:
        app: ubuntu-pod
    spec:
      containers:
        - name: ubuntu-container
          image: ubuntu:22.04
          command: [ '/bin/sh', '-c', 'apt update && apt install -y iptables && apt install -y iputils-ping && apt install -y net-tools && sleep 3600' ]
          ports:
            - containerPort: 8290
              protocol: TCP
          securityContext:
            runAsUser: 0
            capabilities:
              add:
                - NET_ADMIN
