apiVersion: v1
kind: Service
metadata:
  name: simple-forward-service-3
  labels:
    app: simple-forward-3
spec:
  type: NodePort
  selector:
    app: simple-forward-3
  ports:
    - port: 8190
      nodePort: 30193