apiVersion: v1
kind: Service
metadata:
  name: simple-forward-service
  labels:
    app: simple-forward
spec:
  type: NodePort
  selector:
    app: simple-forward
  ports:
    - port: 8390
      nodePort: 30390
      protocol: UDP