apiVersion: v1
kind: Service
metadata:
  name: simple-forward-service-1
  labels:
    app: simple-forward-1
spec:
  type: NodePort
  selector:
    app: simple-forward-1
  ports:
    - port: 8190
      nodePort: 30191