apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      appCluster: postgres-cluster
  template:
    metadata:
      labels:
        app: postgres
        appCluster: postgres-cluster
    spec:
      containers:
        - name: postgres
          image: postgres:15.0
          env:
            - name: POSTGRES_DB
              value: prim  # Change to your desired database name
            - name: POSTGRES_USER
              value: prim  # Change to your desired username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-postgres
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-postgres
          configMap:
            name: postgres-initdb
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: postgres-storage
        resources:
          requests:
            storage: 5Gi


#apiVersion: apps/v1
#kind: StatefulSet
#metadata:
#  name: postgresql
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: postgresql
#  serviceName: postgresql
#  template:
#    metadata:
#      labels:
#        app: postgresql
#    spec:
#      containers:
#        - name: postgres
#          image: postgres:15.0
#          env:
#            - name: POSTGRES_DB
#              value: prim
#            - name: POSTGRES_USER
#              value: prim
#            - name: POSTGRES_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: postgres-password
#          ports:
#            - containerPort: 5432
#          volumeMounts:
#            - name: data
#              mountPath: /var/lib/postgresql/data
#          lifecycle:
#            postStart:
#              exec:
#                command: [ "/bin/bash", "-c", "if [[ ! -f /var/lib/postgresql/data/initialized ]]; then psql -U prim -d prim < /docker-entrypoint-initdb.d/init.sql && touch /var/lib/postgresql/data/initialized; fi" ]
#  volumeClaimTemplates:
#    - metadata:
#        name: postgres-data
#      spec:
#        accessModes:
#          - ReadWriteOnce
#        storageClassName: postgres-storage
#        resources:
#          requests:
#            storage: 5Gi

