apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv0001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-storage
  hostPath:
    path: /data/postgres-pv0001/