#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres-service
#  labels:
#    app: postgres
#spec:
#  ports:
#    - name: postgres-port
#      port: 5432
#  clusterIP: None
#  selector:
#    app: postgres
#    appCluster: postgres-cluster

apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgres
spec:
  selector:
    app: postgres
    appCluster: postgres-cluster
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30032
  type: NodePort
