apiVersion: v1
kind: Service
metadata:
  name: kafka-mq-access-service-1
  labels:
    app: kafka-mq-0
spec:
  type: NodePort
  selector:
    app: kafka
    appCluster: kafka-cluster
  ports:
    - port: 9092
      nodePort: 30092
      protocol: TCP