apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      appCluster: kafka-cluster
  template:
    metadata:
      labels:
        app: kafka
        appCluster: kafka-cluster
    spec:
#      initContainers:
#        - name: parse-hostname
#          image: busybox:latest
#          command: ['/bin/sh', '-c', 'hostname_input=$(hostname); pattern="^([^-]+-)*[0-9]+$"; if [[ $hostname_input =~ $pattern ]]; then node_id=${hostname_input##*-}; echo $node_id > /shared/KAFKA_CFG_NODE_ID; else echo "Error: Hostname does not match the expected format: $hostname_input"; fi']
#          volumeMounts:
#            - name: shared-volume
#              mountPath: /shared
#              readOnly: false
      containers:
        - name: kafka
          image: bitnami/kafka:3.5.0
          ports:
            - containerPort: 9092
            - containerPort: 9093
          command: ['/bin/sh', '-c', 'export KAFKA_CFG_NODE_ID=$(cat /shared/KAFKA_CFG_NODE_ID)']
          env:
            # KRaft settings
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: controller,broker
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 0@kafka-0.kafka-service.default.svc.cluster.local:9093
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
#            - name: KAFKA_KRAFT_CLUSTER_ID
#              value: abcdefghijklmnopqrstuv
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://$(POD_IP):9092,CONTROLLER://$(POD_IP):9093
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
              readOnly: false
#            - name: kafka-config
#              mountPath: /bitnami/kafka/config
#              readOnly: false
#            - name: shared-volume
#              mountPath: /shared
#              readOnly: false
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-pvc
#        - name: kafka-config
#          persistentVolumeClaim:
#            claimName: kafka-config-pvc
#        - name: shared-volume
#          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: kafka-storage
        resources:
          requests:
            storage: 5Gi
#    - metadata:
#        name: kafka-config
#      spec:
#        accessModes:
#          - ReadWriteOnce
#        storageClassName: kafka-config-storage
#        resources:
#          requests:
#            storage: 8Mi