apiVersion: v1
kind: Service
metadata:
  name: kafka-mq-service
  labels:
    app: kafka
spec:
  ports:
    - name: kafka-port-1
      port: 9092
    - name: kafka-port-2
      port: 9093
  clusterIP: None
  selector:
    app: kafka
    appCluster: kafka-cluster