apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-app
spec:
  serviceName: redis-service
  replicas: 6
  selector:
    matchLabels:
      app: redis
      appCluster: redis-cluster
  template:
    metadata:
      labels:
        app: redis
        appCluster: redis-cluster
    spec:
      terminationGracePeriodSeconds: 20
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis
                topologyKey: kubernetes.io/hostname
      containers:
        - name: redis
          image: redis:7.0.0
          command:
            - "redis-server"                  #redis启动命令
          args:
            - "/etc/redis/redis.conf"         #redis-server后面跟的参数,换行代表空格
            - "--protected-mode"              #允许外网访问
            - "no"
          resources:
            requests:                         # 每个pod请求的资源
              cpu: 200m                      # m代表千分之，这里申请2个逻辑核
              memory: 1Gi                     # 内存申请4G大小
            limits:                           # 资源限制
              cpu: 2000m
              memory: 4Gi
          ports:
            - name: redis
              containerPort: 6379
              protocol: "TCP"
            - name: cluster
              containerPort: 16379
              protocol: "TCP"
          volumeMounts:
            - name: redis-conf              # 把下面创建的redis.conf配置文件挂载到容器的/etc/redis目录下
              mountPath: /etc/redis
            - name: redis-data              # 把叫做redis-data的volume挂载到容器的/var/lib/redis目录
              mountPath: /var/lib/redis
      volumes:
        - name: redis-conf                  # 船舰一个名为redis-conf的volumes
          configMap:
            name: redis-config  # 引用上面创建的configMap卷
            items:
              - key: redis.conf             # configmap里面的redis.conf
                path: redis.conf            # configmap里面的redis.conf放到volumes中叫做redistribution.conf
  volumeClaimTemplates:                   # pod使用哪个pvc，这里是通过StorageClass自动创建pvc并对应上pv
    - metadata:
        name: redis-data                    # pvc创建一个volumes叫做redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 5Gi
